# Generated by Django 4.2.7 on 2024-05-26 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_image_url_alter_service_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image_url',
        ),
    ]
