# Generated by Django 4.2.7 on 2024-05-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0001_initial'),
        ('therapists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='therapists.therapist'),
        ),
    ]
